import type { DeploymentTopology } from "@/lib/api-client";
import { useTopologyViewerEffects } from "./use-topology-viewer-effects";
import { useTopologyViewerGraph } from "./use-topology-viewer-graph";
import { useTopologyViewerSurfaceActionWiring } from "./use-topology-viewer-surface-action-wiring";
import { useTopologyViewerSurfaceDialogCoordination } from "./use-topology-viewer-surface-dialog-coordination";
import { useTopologyViewerSurfacePrimitives } from "./use-topology-viewer-surface-primitives";

export type TopologyViewerSurfacePage = ReturnType<
	typeof useTopologyViewerSurface
>;

export function useTopologyViewerSurface({
	topology,
	userId,
	deploymentId,
}: {
	topology?: DeploymentTopology | null;
	userId?: string;
	deploymentId?: string;
}) {
	const derived = useTopologyViewerGraph(topology);
	const primitives = useTopologyViewerSurfacePrimitives({
		derivedNodes: derived.nodes,
		derivedEdges: derived.edges,
		userId,
		deploymentId,
	});
	const actionWiring = useTopologyViewerSurfaceActionWiring({
		userId,
		deploymentId,
		ref: primitives.ref,
		setEdges: primitives.setEdges,
		setNodeMenu: primitives.setNodeMenu,
		setEdgeMenu: primitives.setEdgeMenu,
		impair: primitives.impair,
		setImpairSaving: primitives.setImpairSaving,
		positionsKey: primitives.positionsKey,
		setPinnedPositions: primitives.setPinnedPositions,
		setStatsEnabled: primitives.setStatsEnabled,
		setStatsError: primitives.setStatsError,
		setEdgeRates: primitives.setEdgeRates,
		lastStatsRef: primitives.lastStatsRef,
		hoverEdge: primitives.hoverEdge,
		setHoverEdge: primitives.setHoverEdge,
	});

	useTopologyViewerEffects({
		positionsKey: primitives.positionsKey,
		setPinnedPositions: primitives.setPinnedPositions,
		userId,
		deploymentId,
		deepLinkHandledRef: primitives.deepLinkHandledRef,
		setTerminalNode: primitives.setTerminalNode,
		setLogsNode: primitives.setLogsNode,
		setDescribeNode: primitives.setDescribeNode,
		setInterfacesNode: primitives.setInterfacesNode,
		setInterfacesOpen: primitives.setInterfacesOpen,
		setRunningConfigNode: primitives.setRunningConfigNode,
		setRunningConfigOpen: primitives.setRunningConfigOpen,
		edgeMenu: primitives.edgeMenu,
		setEdgeMenu: primitives.setEdgeMenu,
		nodeMenu: primitives.nodeMenu,
		setNodeMenu: primitives.setNodeMenu,
		interfacesOpen: primitives.interfacesOpen,
		interfacesNodeId: primitives.interfacesNode?.id ?? "",
		interfacesAutoRefresh: primitives.interfacesAutoRefresh,
		fetchInterfaces: actionWiring.fetchInterfaces,
		runningConfigOpen: primitives.runningConfigOpen,
		runningConfigNodeId: primitives.runningConfigNode?.id ?? "",
		fetchRunningConfig: actionWiring.fetchRunningConfig,
		derivedNodes: derived.nodes,
		derivedEdges: derived.edges,
		layoutMode: primitives.layoutMode,
		pinnedPositions: primitives.pinnedPositions,
		search: primitives.search,
		setNodes: primitives.setNodes,
		setEdges: primitives.setEdges,
		edgeRates: primitives.edgeRates,
		statsEnabled: primitives.statsEnabled,
		baseEdgeLabelsRef: primitives.baseEdgeLabelsRef,
		edgeFlags: actionWiring.edgeFlags,
		lastStatsRef: primitives.lastStatsRef,
		setStatsError: primitives.setStatsError,
		setEdgeRates: primitives.setEdgeRates,
	});
	const dialogCoordination = useTopologyViewerSurfaceDialogCoordination({
		nodeMenu: primitives.nodeMenu,
		setNodeMenu: primitives.setNodeMenu,
		edgeMenu: primitives.edgeMenu,
		setEdgeMenu: primitives.setEdgeMenu,
		captureEdge: primitives.captureEdge,
		selectedEdge: primitives.selectedEdge,
		capture: primitives.capture,
		saveConfig: actionWiring.saveConfig,
		linkAdmin: actionWiring.linkAdmin,
		captureLink: actionWiring.captureLink,
		downloadPcap: actionWiring.downloadPcap,
		applyImpairment: actionWiring.applyImpairment,
		edgeFlags: actionWiring.edgeFlags,
		setTerminalNode: primitives.setTerminalNode,
		setLogsNode: primitives.setLogsNode,
		setDescribeNode: primitives.setDescribeNode,
		setInterfacesNode: primitives.setInterfacesNode,
		setInterfacesOpen: primitives.setInterfacesOpen,
		setRunningConfigNode: primitives.setRunningConfigNode,
		setRunningConfigOpen: primitives.setRunningConfigOpen,
		setCaptureEdge: primitives.setCaptureEdge,
		setCaptureOpen: primitives.setCaptureOpen,
		setSelectedEdge: primitives.setSelectedEdge,
		setImpairOpen: primitives.setImpairOpen,
	});

	return {
		ref: primitives.ref,
		nodes: primitives.nodes,
		edges: primitives.edges,
		onNodesChange: primitives.onNodesChange,
		onEdgesChange: primitives.onEdgesChange,
		onConnect: actionWiring.onConnect,
		onNodeContextMenu: actionWiring.onNodeContextMenu,
		onEdgeContextMenu: actionWiring.onEdgeContextMenu,
		onEdgeMouseEnter: actionWiring.onEdgeMouseEnter,
		onEdgeMouseMove: actionWiring.onEdgeMouseMove,
		onEdgeMouseLeave: actionWiring.onEdgeMouseLeave,
		onNodeDragStop: actionWiring.onNodeDragStop,
		search: primitives.search,
		setSearch: primitives.setSearch,
		statsEnabled: primitives.statsEnabled,
		toggleStats: actionWiring.toggleStats,
		statsAvailable: Boolean(userId && deploymentId),
		layoutMode: primitives.layoutMode,
		toggleLayout: () =>
			primitives.setLayoutMode((mode) => (mode === "grid" ? "circle" : "grid")),
		resetLayout: actionWiring.resetLayout,
		downloadInventoryWithToast: actionWiring.downloadInventoryWithToast,
		downloadInventoryDisabled: !userId || !deploymentId,
		statsError: primitives.statsError,
		hoverEdge: primitives.hoverEdge,
		edgeRates: primitives.edgeRates,
		uiEventsEnabled: actionWiring.uiEventsEnabled,
		uiEvents: actionWiring.uiEvents.data,
		userId,
		deploymentId,
		terminalNode: primitives.terminalNode,
		setTerminalNode: primitives.setTerminalNode,
		logsNode: primitives.logsNode,
		setLogsNode: primitives.setLogsNode,
		describeNode: primitives.describeNode,
		setDescribeNode: primitives.setDescribeNode,
		interfacesOpen: primitives.interfacesOpen,
		setInterfacesOpen: primitives.setInterfacesOpen,
		interfacesNode: primitives.interfacesNode,
		setInterfacesNode: primitives.setInterfacesNode,
		fetchInterfaces: actionWiring.fetchInterfaces,
		interfacesAutoRefresh: primitives.interfacesAutoRefresh,
		toggleInterfacesAutoRefresh: () =>
			primitives.setInterfacesAutoRefresh((value) => !value),
		runningConfigOpen: primitives.runningConfigOpen,
		setRunningConfigOpen: primitives.setRunningConfigOpen,
		runningConfigNode: primitives.runningConfigNode,
		setRunningConfigNode: primitives.setRunningConfigNode,
		fetchRunningConfig: actionWiring.fetchRunningConfig,
		captureOpen: primitives.captureOpen,
		setCaptureOpen: primitives.setCaptureOpen,
		captureEdge: primitives.captureEdge,
		setCaptureEdge: primitives.setCaptureEdge,
		capture: primitives.capture,
		setCapture: primitives.setCapture,
		captureLinkPending: actionWiring.captureLink.isPending,
		runCapture: dialogCoordination.runCapture,
		impairOpen: primitives.impairOpen,
		setImpairOpen: primitives.setImpairOpen,
		selectedEdge: primitives.selectedEdge,
		setSelectedEdge: primitives.setSelectedEdge,
		impair: primitives.impair,
		setImpair: primitives.setImpair,
		impairSaving: primitives.impairSaving,
		applySelectedImpairment: dialogCoordination.applySelectedImpairment,
		nodeMenu: primitives.nodeMenu,
		edgeMenu: primitives.edgeMenu,
		saveConfigPending: actionWiring.saveConfig.isPending,
		linkAdminPending: actionWiring.linkAdmin.isPending,
		edgeDown: actionWiring.edgeFlags.edgeDown,
		lastCaptureByEdge: actionWiring.edgeFlags.lastCaptureByEdge,
		closeNodeMenu: dialogCoordination.closeNodeMenu,
		closeEdgeMenu: dialogCoordination.closeEdgeMenu,
		openTerminal: dialogCoordination.openTerminal,
		openNodeActionTab: dialogCoordination.openNodeActionTab,
		openLogs: dialogCoordination.openLogs,
		openDescribe: dialogCoordination.openDescribe,
		openInterfaces: dialogCoordination.openInterfaces,
		saveConfigForNode: dialogCoordination.saveConfigForNode,
		openRunningConfig: dialogCoordination.openRunningConfig,
		copyManagementIP: dialogCoordination.copyManagementIP,
		copyNodeName: dialogCoordination.copyNodeName,
		copySshCommand: dialogCoordination.copySshCommand,
		toggleLinkAdmin: dialogCoordination.toggleLinkAdmin,
		openCapture: dialogCoordination.openCapture,
		downloadLastPcap: dialogCoordination.downloadLastPcap,
		openImpairment: dialogCoordination.openImpairment,
		clearImpairment: dialogCoordination.clearImpairment,
	};
}
