/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as SyslogRouteImport } from './routes/syslog'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SnmpRouteImport } from './routes/snmp'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DesignRouteImport } from './routes/design'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardS3RouteImport } from './routes/dashboard/s3'
import { Route as DashboardPkiRouteImport } from './routes/dashboard/pki'
import { Route as DashboardDeploymentsRouteImport } from './routes/dashboard/deployments'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminGovernanceRouteImport } from './routes/admin/governance'
import { Route as DashboardRunsRunIdRouteImport } from './routes/dashboard/runs/$runId'
import { Route as DashboardDeploymentsNewRouteImport } from './routes/dashboard/deployments/new'
import { Route as DashboardDeploymentsDeploymentIdIndexRouteImport } from './routes/dashboard/deployments/$deploymentId.index'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const SyslogRoute = SyslogRouteImport.update({
  id: '/syslog',
  path: '/syslog',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SnmpRoute = SnmpRouteImport.update({
  id: '/snmp',
  path: '/snmp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardS3Route = DashboardS3RouteImport.update({
  id: '/dashboard/s3',
  path: '/dashboard/s3',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPkiRoute = DashboardPkiRouteImport.update({
  id: '/dashboard/pki',
  path: '/dashboard/pki',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/dashboard/deployments',
  path: '/dashboard/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGovernanceRoute = AdminGovernanceRouteImport.update({
  id: '/admin/governance',
  path: '/admin/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRunsRunIdRoute = DashboardRunsRunIdRouteImport.update({
  id: '/dashboard/runs/$runId',
  path: '/dashboard/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDeploymentsNewRoute = DashboardDeploymentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardDeploymentsRoute,
} as any)
const DashboardDeploymentsDeploymentIdIndexRoute =
  DashboardDeploymentsDeploymentIdIndexRouteImport.update({
    id: '/$deploymentId/',
    path: '/$deploymentId/',
    getParentRoute: () => DashboardDeploymentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/snmp': typeof SnmpRoute
  '/status': typeof StatusRoute
  '/syslog': typeof SyslogRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRouteWithChildren
  '/dashboard/pki': typeof DashboardPkiRoute
  '/dashboard/s3': typeof DashboardS3Route
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/deployments/new': typeof DashboardDeploymentsNewRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRoute
  '/dashboard/deployments/$deploymentId': typeof DashboardDeploymentsDeploymentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/snmp': typeof SnmpRoute
  '/status': typeof StatusRoute
  '/syslog': typeof SyslogRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRouteWithChildren
  '/dashboard/pki': typeof DashboardPkiRoute
  '/dashboard/s3': typeof DashboardS3Route
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/deployments/new': typeof DashboardDeploymentsNewRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRoute
  '/dashboard/deployments/$deploymentId': typeof DashboardDeploymentsDeploymentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/snmp': typeof SnmpRoute
  '/status': typeof StatusRoute
  '/syslog': typeof SyslogRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRouteWithChildren
  '/dashboard/pki': typeof DashboardPkiRoute
  '/dashboard/s3': typeof DashboardS3Route
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/deployments/new': typeof DashboardDeploymentsNewRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRoute
  '/dashboard/deployments/$deploymentId/': typeof DashboardDeploymentsDeploymentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/notifications'
    | '/snmp'
    | '/status'
    | '/syslog'
    | '/webhooks'
    | '/admin/governance'
    | '/admin/settings'
    | '/dashboard/deployments'
    | '/dashboard/pki'
    | '/dashboard/s3'
    | '/admin'
    | '/dashboard'
    | '/dashboard/deployments/new'
    | '/dashboard/runs/$runId'
    | '/dashboard/deployments/$deploymentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/notifications'
    | '/snmp'
    | '/status'
    | '/syslog'
    | '/webhooks'
    | '/admin/governance'
    | '/admin/settings'
    | '/dashboard/deployments'
    | '/dashboard/pki'
    | '/dashboard/s3'
    | '/admin'
    | '/dashboard'
    | '/dashboard/deployments/new'
    | '/dashboard/runs/$runId'
    | '/dashboard/deployments/$deploymentId'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/notifications'
    | '/snmp'
    | '/status'
    | '/syslog'
    | '/webhooks'
    | '/admin/governance'
    | '/admin/settings'
    | '/dashboard/deployments'
    | '/dashboard/pki'
    | '/dashboard/s3'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/deployments/new'
    | '/dashboard/runs/$runId'
    | '/dashboard/deployments/$deploymentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  NotificationsRoute: typeof NotificationsRoute
  SnmpRoute: typeof SnmpRoute
  StatusRoute: typeof StatusRoute
  SyslogRoute: typeof SyslogRoute
  WebhooksRoute: typeof WebhooksRoute
  AdminGovernanceRoute: typeof AdminGovernanceRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRouteWithChildren
  DashboardPkiRoute: typeof DashboardPkiRoute
  DashboardS3Route: typeof DashboardS3Route
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRunsRunIdRoute: typeof DashboardRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syslog': {
      id: '/syslog'
      path: '/syslog'
      fullPath: '/syslog'
      preLoaderRoute: typeof SyslogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snmp': {
      id: '/snmp'
      path: '/snmp'
      fullPath: '/snmp'
      preLoaderRoute: typeof SnmpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/s3': {
      id: '/dashboard/s3'
      path: '/dashboard/s3'
      fullPath: '/dashboard/s3'
      preLoaderRoute: typeof DashboardS3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pki': {
      id: '/dashboard/pki'
      path: '/dashboard/pki'
      fullPath: '/dashboard/pki'
      preLoaderRoute: typeof DashboardPkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/deployments': {
      id: '/dashboard/deployments'
      path: '/dashboard/deployments'
      fullPath: '/dashboard/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/governance': {
      id: '/admin/governance'
      path: '/admin/governance'
      fullPath: '/admin/governance'
      preLoaderRoute: typeof AdminGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/runs/$runId': {
      id: '/dashboard/runs/$runId'
      path: '/dashboard/runs/$runId'
      fullPath: '/dashboard/runs/$runId'
      preLoaderRoute: typeof DashboardRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/deployments/new': {
      id: '/dashboard/deployments/new'
      path: '/new'
      fullPath: '/dashboard/deployments/new'
      preLoaderRoute: typeof DashboardDeploymentsNewRouteImport
      parentRoute: typeof DashboardDeploymentsRoute
    }
    '/dashboard/deployments/$deploymentId/': {
      id: '/dashboard/deployments/$deploymentId/'
      path: '/$deploymentId'
      fullPath: '/dashboard/deployments/$deploymentId'
      preLoaderRoute: typeof DashboardDeploymentsDeploymentIdIndexRouteImport
      parentRoute: typeof DashboardDeploymentsRoute
    }
  }
}

interface DashboardDeploymentsRouteChildren {
  DashboardDeploymentsNewRoute: typeof DashboardDeploymentsNewRoute
  DashboardDeploymentsDeploymentIdIndexRoute: typeof DashboardDeploymentsDeploymentIdIndexRoute
}

const DashboardDeploymentsRouteChildren: DashboardDeploymentsRouteChildren = {
  DashboardDeploymentsNewRoute: DashboardDeploymentsNewRoute,
  DashboardDeploymentsDeploymentIdIndexRoute:
    DashboardDeploymentsDeploymentIdIndexRoute,
}

const DashboardDeploymentsRouteWithChildren =
  DashboardDeploymentsRoute._addFileChildren(DashboardDeploymentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  NotificationsRoute: NotificationsRoute,
  SnmpRoute: SnmpRoute,
  StatusRoute: StatusRoute,
  SyslogRoute: SyslogRoute,
  WebhooksRoute: WebhooksRoute,
  AdminGovernanceRoute: AdminGovernanceRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  DashboardDeploymentsRoute: DashboardDeploymentsRouteWithChildren,
  DashboardPkiRoute: DashboardPkiRoute,
  DashboardS3Route: DashboardS3Route,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRunsRunIdRoute: DashboardRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
