/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as SyslogRouteImport } from './routes/syslog'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SnmpRouteImport } from './routes/snmp'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DesignRouteImport } from './routes/design'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardServicenowRouteImport } from './routes/dashboard/servicenow'
import { Route as DashboardS3RouteImport } from './routes/dashboard/s3'
import { Route as DashboardPolicyReportsRouteImport } from './routes/dashboard/policy-reports'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard/integrations'
import { Route as DashboardForwardRouteImport } from './routes/dashboard/forward'
import { Route as DashboardElasticRouteImport } from './routes/dashboard/elastic'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminGovernanceRouteImport } from './routes/admin/governance'
import { Route as DashboardRunsIndexRouteImport } from './routes/dashboard/runs/index'
import { Route as DashboardFwdIndexRouteImport } from './routes/dashboard/fwd/index'
import { Route as DashboardDocsIndexRouteImport } from './routes/dashboard/docs/index'
import { Route as DashboardDeploymentsIndexRouteImport } from './routes/dashboard/deployments/index'
import { Route as DashboardRunsRunIdRouteImport } from './routes/dashboard/runs/$runId'
import { Route as DashboardLabsMapRouteImport } from './routes/dashboard/labs/map'
import { Route as DashboardLabsDesignerRouteImport } from './routes/dashboard/labs/designer'
import { Route as DashboardDocsSlugRouteImport } from './routes/dashboard/docs/$slug'
import { Route as DashboardDeploymentsNewRouteImport } from './routes/dashboard/deployments/new'
import { Route as DashboardDeploymentsDeploymentIdIndexRouteImport } from './routes/dashboard/deployments/$deploymentId.index'
import { Route as DashboardFwdNetworkRefTrafficScenariosRouteImport } from './routes/dashboard/fwd/$networkRef.traffic-scenarios'
import { Route as DashboardFwdNetworkRefCapacityRouteImport } from './routes/dashboard/fwd/$networkRef.capacity'
import { Route as DashboardFwdNetworkRefAssuranceStudioRouteImport } from './routes/dashboard/fwd/$networkRef.assurance-studio'
import { Route as DashboardFwdNetworkRefAssuranceRouteImport } from './routes/dashboard/fwd/$networkRef.assurance'
import { Route as DashboardDeploymentsDeploymentIdMapRouteImport } from './routes/dashboard/deployments/$deploymentId.map'
import { Route as DashboardDeploymentsDeploymentIdCapacityRouteImport } from './routes/dashboard/deployments/$deploymentId.capacity'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const SyslogRoute = SyslogRouteImport.update({
  id: '/syslog',
  path: '/syslog',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SnmpRoute = SnmpRouteImport.update({
  id: '/snmp',
  path: '/snmp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServicenowRoute = DashboardServicenowRouteImport.update({
  id: '/dashboard/servicenow',
  path: '/dashboard/servicenow',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardS3Route = DashboardS3RouteImport.update({
  id: '/dashboard/s3',
  path: '/dashboard/s3',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPolicyReportsRoute = DashboardPolicyReportsRouteImport.update({
  id: '/dashboard/policy-reports',
  path: '/dashboard/policy-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/dashboard/integrations',
  path: '/dashboard/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardForwardRoute = DashboardForwardRouteImport.update({
  id: '/dashboard/forward',
  path: '/dashboard/forward',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardElasticRoute = DashboardElasticRouteImport.update({
  id: '/dashboard/elastic',
  path: '/dashboard/elastic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGovernanceRoute = AdminGovernanceRouteImport.update({
  id: '/admin/governance',
  path: '/admin/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRunsIndexRoute = DashboardRunsIndexRouteImport.update({
  id: '/dashboard/runs/',
  path: '/dashboard/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFwdIndexRoute = DashboardFwdIndexRouteImport.update({
  id: '/dashboard/fwd/',
  path: '/dashboard/fwd/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDocsIndexRoute = DashboardDocsIndexRouteImport.update({
  id: '/dashboard/docs/',
  path: '/dashboard/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDeploymentsIndexRoute =
  DashboardDeploymentsIndexRouteImport.update({
    id: '/dashboard/deployments/',
    path: '/dashboard/deployments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardRunsRunIdRoute = DashboardRunsRunIdRouteImport.update({
  id: '/dashboard/runs/$runId',
  path: '/dashboard/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLabsMapRoute = DashboardLabsMapRouteImport.update({
  id: '/dashboard/labs/map',
  path: '/dashboard/labs/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLabsDesignerRoute = DashboardLabsDesignerRouteImport.update({
  id: '/dashboard/labs/designer',
  path: '/dashboard/labs/designer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDocsSlugRoute = DashboardDocsSlugRouteImport.update({
  id: '/dashboard/docs/$slug',
  path: '/dashboard/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDeploymentsNewRoute = DashboardDeploymentsNewRouteImport.update({
  id: '/dashboard/deployments/new',
  path: '/dashboard/deployments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDeploymentsDeploymentIdIndexRoute =
  DashboardDeploymentsDeploymentIdIndexRouteImport.update({
    id: '/dashboard/deployments/$deploymentId/',
    path: '/dashboard/deployments/$deploymentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardFwdNetworkRefTrafficScenariosRoute =
  DashboardFwdNetworkRefTrafficScenariosRouteImport.update({
    id: '/dashboard/fwd/$networkRef/traffic-scenarios',
    path: '/dashboard/fwd/$networkRef/traffic-scenarios',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardFwdNetworkRefCapacityRoute =
  DashboardFwdNetworkRefCapacityRouteImport.update({
    id: '/dashboard/fwd/$networkRef/capacity',
    path: '/dashboard/fwd/$networkRef/capacity',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardFwdNetworkRefAssuranceStudioRoute =
  DashboardFwdNetworkRefAssuranceStudioRouteImport.update({
    id: '/dashboard/fwd/$networkRef/assurance-studio',
    path: '/dashboard/fwd/$networkRef/assurance-studio',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardFwdNetworkRefAssuranceRoute =
  DashboardFwdNetworkRefAssuranceRouteImport.update({
    id: '/dashboard/fwd/$networkRef/assurance',
    path: '/dashboard/fwd/$networkRef/assurance',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardDeploymentsDeploymentIdMapRoute =
  DashboardDeploymentsDeploymentIdMapRouteImport.update({
    id: '/dashboard/deployments/$deploymentId/map',
    path: '/dashboard/deployments/$deploymentId/map',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardDeploymentsDeploymentIdCapacityRoute =
  DashboardDeploymentsDeploymentIdCapacityRouteImport.update({
    id: '/dashboard/deployments/$deploymentId/capacity',
    path: '/dashboard/deployments/$deploymentId/capacity',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/snmp': typeof SnmpRoute
  '/status': typeof StatusRoute
  '/syslog': typeof SyslogRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/elastic': typeof DashboardElasticRoute
  '/dashboard/forward': typeof DashboardForwardRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/policy-reports': typeof DashboardPolicyReportsRoute
  '/dashboard/s3': typeof DashboardS3Route
  '/dashboard/servicenow': typeof DashboardServicenowRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/dashboard/deployments/new': typeof DashboardDeploymentsNewRoute
  '/dashboard/docs/$slug': typeof DashboardDocsSlugRoute
  '/dashboard/labs/designer': typeof DashboardLabsDesignerRoute
  '/dashboard/labs/map': typeof DashboardLabsMapRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRoute
  '/dashboard/deployments': typeof DashboardDeploymentsIndexRoute
  '/dashboard/docs': typeof DashboardDocsIndexRoute
  '/dashboard/fwd': typeof DashboardFwdIndexRoute
  '/dashboard/runs': typeof DashboardRunsIndexRoute
  '/dashboard/deployments/$deploymentId/capacity': typeof DashboardDeploymentsDeploymentIdCapacityRoute
  '/dashboard/deployments/$deploymentId/map': typeof DashboardDeploymentsDeploymentIdMapRoute
  '/dashboard/fwd/$networkRef/assurance': typeof DashboardFwdNetworkRefAssuranceRoute
  '/dashboard/fwd/$networkRef/assurance-studio': typeof DashboardFwdNetworkRefAssuranceStudioRoute
  '/dashboard/fwd/$networkRef/capacity': typeof DashboardFwdNetworkRefCapacityRoute
  '/dashboard/fwd/$networkRef/traffic-scenarios': typeof DashboardFwdNetworkRefTrafficScenariosRoute
  '/dashboard/deployments/$deploymentId': typeof DashboardDeploymentsDeploymentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/snmp': typeof SnmpRoute
  '/status': typeof StatusRoute
  '/syslog': typeof SyslogRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/elastic': typeof DashboardElasticRoute
  '/dashboard/forward': typeof DashboardForwardRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/policy-reports': typeof DashboardPolicyReportsRoute
  '/dashboard/s3': typeof DashboardS3Route
  '/dashboard/servicenow': typeof DashboardServicenowRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/dashboard/deployments/new': typeof DashboardDeploymentsNewRoute
  '/dashboard/docs/$slug': typeof DashboardDocsSlugRoute
  '/dashboard/labs/designer': typeof DashboardLabsDesignerRoute
  '/dashboard/labs/map': typeof DashboardLabsMapRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRoute
  '/dashboard/deployments': typeof DashboardDeploymentsIndexRoute
  '/dashboard/docs': typeof DashboardDocsIndexRoute
  '/dashboard/fwd': typeof DashboardFwdIndexRoute
  '/dashboard/runs': typeof DashboardRunsIndexRoute
  '/dashboard/deployments/$deploymentId/capacity': typeof DashboardDeploymentsDeploymentIdCapacityRoute
  '/dashboard/deployments/$deploymentId/map': typeof DashboardDeploymentsDeploymentIdMapRoute
  '/dashboard/fwd/$networkRef/assurance': typeof DashboardFwdNetworkRefAssuranceRoute
  '/dashboard/fwd/$networkRef/assurance-studio': typeof DashboardFwdNetworkRefAssuranceStudioRoute
  '/dashboard/fwd/$networkRef/capacity': typeof DashboardFwdNetworkRefCapacityRoute
  '/dashboard/fwd/$networkRef/traffic-scenarios': typeof DashboardFwdNetworkRefTrafficScenariosRoute
  '/dashboard/deployments/$deploymentId': typeof DashboardDeploymentsDeploymentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/snmp': typeof SnmpRoute
  '/status': typeof StatusRoute
  '/syslog': typeof SyslogRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/elastic': typeof DashboardElasticRoute
  '/dashboard/forward': typeof DashboardForwardRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/policy-reports': typeof DashboardPolicyReportsRoute
  '/dashboard/s3': typeof DashboardS3Route
  '/dashboard/servicenow': typeof DashboardServicenowRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/deployments/new': typeof DashboardDeploymentsNewRoute
  '/dashboard/docs/$slug': typeof DashboardDocsSlugRoute
  '/dashboard/labs/designer': typeof DashboardLabsDesignerRoute
  '/dashboard/labs/map': typeof DashboardLabsMapRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRoute
  '/dashboard/deployments/': typeof DashboardDeploymentsIndexRoute
  '/dashboard/docs/': typeof DashboardDocsIndexRoute
  '/dashboard/fwd/': typeof DashboardFwdIndexRoute
  '/dashboard/runs/': typeof DashboardRunsIndexRoute
  '/dashboard/deployments/$deploymentId/capacity': typeof DashboardDeploymentsDeploymentIdCapacityRoute
  '/dashboard/deployments/$deploymentId/map': typeof DashboardDeploymentsDeploymentIdMapRoute
  '/dashboard/fwd/$networkRef/assurance': typeof DashboardFwdNetworkRefAssuranceRoute
  '/dashboard/fwd/$networkRef/assurance-studio': typeof DashboardFwdNetworkRefAssuranceStudioRoute
  '/dashboard/fwd/$networkRef/capacity': typeof DashboardFwdNetworkRefCapacityRoute
  '/dashboard/fwd/$networkRef/traffic-scenarios': typeof DashboardFwdNetworkRefTrafficScenariosRoute
  '/dashboard/deployments/$deploymentId/': typeof DashboardDeploymentsDeploymentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/notifications'
    | '/snmp'
    | '/status'
    | '/syslog'
    | '/webhooks'
    | '/admin/governance'
    | '/admin/settings'
    | '/dashboard/elastic'
    | '/dashboard/forward'
    | '/dashboard/integrations'
    | '/dashboard/policy-reports'
    | '/dashboard/s3'
    | '/dashboard/servicenow'
    | '/dashboard/settings'
    | '/docs/$slug'
    | '/admin'
    | '/dashboard'
    | '/docs'
    | '/dashboard/deployments/new'
    | '/dashboard/docs/$slug'
    | '/dashboard/labs/designer'
    | '/dashboard/labs/map'
    | '/dashboard/runs/$runId'
    | '/dashboard/deployments'
    | '/dashboard/docs'
    | '/dashboard/fwd'
    | '/dashboard/runs'
    | '/dashboard/deployments/$deploymentId/capacity'
    | '/dashboard/deployments/$deploymentId/map'
    | '/dashboard/fwd/$networkRef/assurance'
    | '/dashboard/fwd/$networkRef/assurance-studio'
    | '/dashboard/fwd/$networkRef/capacity'
    | '/dashboard/fwd/$networkRef/traffic-scenarios'
    | '/dashboard/deployments/$deploymentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/notifications'
    | '/snmp'
    | '/status'
    | '/syslog'
    | '/webhooks'
    | '/admin/governance'
    | '/admin/settings'
    | '/dashboard/elastic'
    | '/dashboard/forward'
    | '/dashboard/integrations'
    | '/dashboard/policy-reports'
    | '/dashboard/s3'
    | '/dashboard/servicenow'
    | '/dashboard/settings'
    | '/docs/$slug'
    | '/admin'
    | '/dashboard'
    | '/docs'
    | '/dashboard/deployments/new'
    | '/dashboard/docs/$slug'
    | '/dashboard/labs/designer'
    | '/dashboard/labs/map'
    | '/dashboard/runs/$runId'
    | '/dashboard/deployments'
    | '/dashboard/docs'
    | '/dashboard/fwd'
    | '/dashboard/runs'
    | '/dashboard/deployments/$deploymentId/capacity'
    | '/dashboard/deployments/$deploymentId/map'
    | '/dashboard/fwd/$networkRef/assurance'
    | '/dashboard/fwd/$networkRef/assurance-studio'
    | '/dashboard/fwd/$networkRef/capacity'
    | '/dashboard/fwd/$networkRef/traffic-scenarios'
    | '/dashboard/deployments/$deploymentId'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/notifications'
    | '/snmp'
    | '/status'
    | '/syslog'
    | '/webhooks'
    | '/admin/governance'
    | '/admin/settings'
    | '/dashboard/elastic'
    | '/dashboard/forward'
    | '/dashboard/integrations'
    | '/dashboard/policy-reports'
    | '/dashboard/s3'
    | '/dashboard/servicenow'
    | '/dashboard/settings'
    | '/docs/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/deployments/new'
    | '/dashboard/docs/$slug'
    | '/dashboard/labs/designer'
    | '/dashboard/labs/map'
    | '/dashboard/runs/$runId'
    | '/dashboard/deployments/'
    | '/dashboard/docs/'
    | '/dashboard/fwd/'
    | '/dashboard/runs/'
    | '/dashboard/deployments/$deploymentId/capacity'
    | '/dashboard/deployments/$deploymentId/map'
    | '/dashboard/fwd/$networkRef/assurance'
    | '/dashboard/fwd/$networkRef/assurance-studio'
    | '/dashboard/fwd/$networkRef/capacity'
    | '/dashboard/fwd/$networkRef/traffic-scenarios'
    | '/dashboard/deployments/$deploymentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  NotificationsRoute: typeof NotificationsRoute
  SnmpRoute: typeof SnmpRoute
  StatusRoute: typeof StatusRoute
  SyslogRoute: typeof SyslogRoute
  WebhooksRoute: typeof WebhooksRoute
  AdminGovernanceRoute: typeof AdminGovernanceRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  DashboardElasticRoute: typeof DashboardElasticRoute
  DashboardForwardRoute: typeof DashboardForwardRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardPolicyReportsRoute: typeof DashboardPolicyReportsRoute
  DashboardS3Route: typeof DashboardS3Route
  DashboardServicenowRoute: typeof DashboardServicenowRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DocsSlugRoute: typeof DocsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DashboardDeploymentsNewRoute: typeof DashboardDeploymentsNewRoute
  DashboardDocsSlugRoute: typeof DashboardDocsSlugRoute
  DashboardLabsDesignerRoute: typeof DashboardLabsDesignerRoute
  DashboardLabsMapRoute: typeof DashboardLabsMapRoute
  DashboardRunsRunIdRoute: typeof DashboardRunsRunIdRoute
  DashboardDeploymentsIndexRoute: typeof DashboardDeploymentsIndexRoute
  DashboardDocsIndexRoute: typeof DashboardDocsIndexRoute
  DashboardFwdIndexRoute: typeof DashboardFwdIndexRoute
  DashboardRunsIndexRoute: typeof DashboardRunsIndexRoute
  DashboardDeploymentsDeploymentIdCapacityRoute: typeof DashboardDeploymentsDeploymentIdCapacityRoute
  DashboardDeploymentsDeploymentIdMapRoute: typeof DashboardDeploymentsDeploymentIdMapRoute
  DashboardFwdNetworkRefAssuranceRoute: typeof DashboardFwdNetworkRefAssuranceRoute
  DashboardFwdNetworkRefAssuranceStudioRoute: typeof DashboardFwdNetworkRefAssuranceStudioRoute
  DashboardFwdNetworkRefCapacityRoute: typeof DashboardFwdNetworkRefCapacityRoute
  DashboardFwdNetworkRefTrafficScenariosRoute: typeof DashboardFwdNetworkRefTrafficScenariosRoute
  DashboardDeploymentsDeploymentIdIndexRoute: typeof DashboardDeploymentsDeploymentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syslog': {
      id: '/syslog'
      path: '/syslog'
      fullPath: '/syslog'
      preLoaderRoute: typeof SyslogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snmp': {
      id: '/snmp'
      path: '/snmp'
      fullPath: '/snmp'
      preLoaderRoute: typeof SnmpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/servicenow': {
      id: '/dashboard/servicenow'
      path: '/dashboard/servicenow'
      fullPath: '/dashboard/servicenow'
      preLoaderRoute: typeof DashboardServicenowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/s3': {
      id: '/dashboard/s3'
      path: '/dashboard/s3'
      fullPath: '/dashboard/s3'
      preLoaderRoute: typeof DashboardS3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/policy-reports': {
      id: '/dashboard/policy-reports'
      path: '/dashboard/policy-reports'
      fullPath: '/dashboard/policy-reports'
      preLoaderRoute: typeof DashboardPolicyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/dashboard/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/forward': {
      id: '/dashboard/forward'
      path: '/dashboard/forward'
      fullPath: '/dashboard/forward'
      preLoaderRoute: typeof DashboardForwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/elastic': {
      id: '/dashboard/elastic'
      path: '/dashboard/elastic'
      fullPath: '/dashboard/elastic'
      preLoaderRoute: typeof DashboardElasticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/governance': {
      id: '/admin/governance'
      path: '/admin/governance'
      fullPath: '/admin/governance'
      preLoaderRoute: typeof AdminGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/runs/': {
      id: '/dashboard/runs/'
      path: '/dashboard/runs'
      fullPath: '/dashboard/runs'
      preLoaderRoute: typeof DashboardRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/fwd/': {
      id: '/dashboard/fwd/'
      path: '/dashboard/fwd'
      fullPath: '/dashboard/fwd'
      preLoaderRoute: typeof DashboardFwdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/docs/': {
      id: '/dashboard/docs/'
      path: '/dashboard/docs'
      fullPath: '/dashboard/docs'
      preLoaderRoute: typeof DashboardDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/deployments/': {
      id: '/dashboard/deployments/'
      path: '/dashboard/deployments'
      fullPath: '/dashboard/deployments'
      preLoaderRoute: typeof DashboardDeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/runs/$runId': {
      id: '/dashboard/runs/$runId'
      path: '/dashboard/runs/$runId'
      fullPath: '/dashboard/runs/$runId'
      preLoaderRoute: typeof DashboardRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/labs/map': {
      id: '/dashboard/labs/map'
      path: '/dashboard/labs/map'
      fullPath: '/dashboard/labs/map'
      preLoaderRoute: typeof DashboardLabsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/labs/designer': {
      id: '/dashboard/labs/designer'
      path: '/dashboard/labs/designer'
      fullPath: '/dashboard/labs/designer'
      preLoaderRoute: typeof DashboardLabsDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/docs/$slug': {
      id: '/dashboard/docs/$slug'
      path: '/dashboard/docs/$slug'
      fullPath: '/dashboard/docs/$slug'
      preLoaderRoute: typeof DashboardDocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/deployments/new': {
      id: '/dashboard/deployments/new'
      path: '/dashboard/deployments/new'
      fullPath: '/dashboard/deployments/new'
      preLoaderRoute: typeof DashboardDeploymentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/deployments/$deploymentId/': {
      id: '/dashboard/deployments/$deploymentId/'
      path: '/dashboard/deployments/$deploymentId'
      fullPath: '/dashboard/deployments/$deploymentId'
      preLoaderRoute: typeof DashboardDeploymentsDeploymentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/fwd/$networkRef/traffic-scenarios': {
      id: '/dashboard/fwd/$networkRef/traffic-scenarios'
      path: '/dashboard/fwd/$networkRef/traffic-scenarios'
      fullPath: '/dashboard/fwd/$networkRef/traffic-scenarios'
      preLoaderRoute: typeof DashboardFwdNetworkRefTrafficScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/fwd/$networkRef/capacity': {
      id: '/dashboard/fwd/$networkRef/capacity'
      path: '/dashboard/fwd/$networkRef/capacity'
      fullPath: '/dashboard/fwd/$networkRef/capacity'
      preLoaderRoute: typeof DashboardFwdNetworkRefCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/fwd/$networkRef/assurance-studio': {
      id: '/dashboard/fwd/$networkRef/assurance-studio'
      path: '/dashboard/fwd/$networkRef/assurance-studio'
      fullPath: '/dashboard/fwd/$networkRef/assurance-studio'
      preLoaderRoute: typeof DashboardFwdNetworkRefAssuranceStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/fwd/$networkRef/assurance': {
      id: '/dashboard/fwd/$networkRef/assurance'
      path: '/dashboard/fwd/$networkRef/assurance'
      fullPath: '/dashboard/fwd/$networkRef/assurance'
      preLoaderRoute: typeof DashboardFwdNetworkRefAssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/deployments/$deploymentId/map': {
      id: '/dashboard/deployments/$deploymentId/map'
      path: '/dashboard/deployments/$deploymentId/map'
      fullPath: '/dashboard/deployments/$deploymentId/map'
      preLoaderRoute: typeof DashboardDeploymentsDeploymentIdMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/deployments/$deploymentId/capacity': {
      id: '/dashboard/deployments/$deploymentId/capacity'
      path: '/dashboard/deployments/$deploymentId/capacity'
      fullPath: '/dashboard/deployments/$deploymentId/capacity'
      preLoaderRoute: typeof DashboardDeploymentsDeploymentIdCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  NotificationsRoute: NotificationsRoute,
  SnmpRoute: SnmpRoute,
  StatusRoute: StatusRoute,
  SyslogRoute: SyslogRoute,
  WebhooksRoute: WebhooksRoute,
  AdminGovernanceRoute: AdminGovernanceRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  DashboardElasticRoute: DashboardElasticRoute,
  DashboardForwardRoute: DashboardForwardRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardPolicyReportsRoute: DashboardPolicyReportsRoute,
  DashboardS3Route: DashboardS3Route,
  DashboardServicenowRoute: DashboardServicenowRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DocsSlugRoute: DocsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DashboardDeploymentsNewRoute: DashboardDeploymentsNewRoute,
  DashboardDocsSlugRoute: DashboardDocsSlugRoute,
  DashboardLabsDesignerRoute: DashboardLabsDesignerRoute,
  DashboardLabsMapRoute: DashboardLabsMapRoute,
  DashboardRunsRunIdRoute: DashboardRunsRunIdRoute,
  DashboardDeploymentsIndexRoute: DashboardDeploymentsIndexRoute,
  DashboardDocsIndexRoute: DashboardDocsIndexRoute,
  DashboardFwdIndexRoute: DashboardFwdIndexRoute,
  DashboardRunsIndexRoute: DashboardRunsIndexRoute,
  DashboardDeploymentsDeploymentIdCapacityRoute:
    DashboardDeploymentsDeploymentIdCapacityRoute,
  DashboardDeploymentsDeploymentIdMapRoute:
    DashboardDeploymentsDeploymentIdMapRoute,
  DashboardFwdNetworkRefAssuranceRoute: DashboardFwdNetworkRefAssuranceRoute,
  DashboardFwdNetworkRefAssuranceStudioRoute:
    DashboardFwdNetworkRefAssuranceStudioRoute,
  DashboardFwdNetworkRefCapacityRoute: DashboardFwdNetworkRefCapacityRoute,
  DashboardFwdNetworkRefTrafficScenariosRoute:
    DashboardFwdNetworkRefTrafficScenariosRoute,
  DashboardDeploymentsDeploymentIdIndexRoute:
    DashboardDeploymentsDeploymentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
