/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as StatusRouteImport } from './routes/status'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardWorkspacesRouteImport } from './routes/dashboard/workspaces'
import { Route as DashboardS3RouteImport } from './routes/dashboard/s3'
import { Route as DashboardPkiRouteImport } from './routes/dashboard/pki'
import { Route as DashboardDeploymentsRouteImport } from './routes/dashboard/deployments'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminGovernanceRouteImport } from './routes/admin/governance'
import { Route as DashboardRunsRunIdRouteImport } from './routes/dashboard/runs/$runId'
import { Route as DashboardDeploymentsNewRouteImport } from './routes/dashboard/deployments/new'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspacesRoute = DashboardWorkspacesRouteImport.update({
  id: '/dashboard/workspaces',
  path: '/dashboard/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardS3Route = DashboardS3RouteImport.update({
  id: '/dashboard/s3',
  path: '/dashboard/s3',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPkiRoute = DashboardPkiRouteImport.update({
  id: '/dashboard/pki',
  path: '/dashboard/pki',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/dashboard/deployments',
  path: '/dashboard/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGovernanceRoute = AdminGovernanceRouteImport.update({
  id: '/admin/governance',
  path: '/admin/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRunsRunIdRoute = DashboardRunsRunIdRouteImport.update({
  id: '/dashboard/runs/$runId',
  path: '/dashboard/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDeploymentsNewRoute = DashboardDeploymentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardDeploymentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRouteWithChildren
  '/dashboard/pki': typeof DashboardPkiRoute
  '/dashboard/s3': typeof DashboardS3Route
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/deployments/new': typeof DashboardDeploymentsNewRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRouteWithChildren
  '/dashboard/pki': typeof DashboardPkiRoute
  '/dashboard/s3': typeof DashboardS3Route
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/deployments/new': typeof DashboardDeploymentsNewRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRouteWithChildren
  '/dashboard/pki': typeof DashboardPkiRoute
  '/dashboard/s3': typeof DashboardS3Route
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/deployments/new': typeof DashboardDeploymentsNewRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/status'
    | '/webhooks'
    | '/admin/governance'
    | '/admin/settings'
    | '/dashboard/deployments'
    | '/dashboard/pki'
    | '/dashboard/s3'
    | '/dashboard/workspaces'
    | '/admin'
    | '/dashboard'
    | '/dashboard/deployments/new'
    | '/dashboard/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/status'
    | '/webhooks'
    | '/admin/governance'
    | '/admin/settings'
    | '/dashboard/deployments'
    | '/dashboard/pki'
    | '/dashboard/s3'
    | '/dashboard/workspaces'
    | '/admin'
    | '/dashboard'
    | '/dashboard/deployments/new'
    | '/dashboard/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/status'
    | '/webhooks'
    | '/admin/governance'
    | '/admin/settings'
    | '/dashboard/deployments'
    | '/dashboard/pki'
    | '/dashboard/s3'
    | '/dashboard/workspaces'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/deployments/new'
    | '/dashboard/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatusRoute: typeof StatusRoute
  WebhooksRoute: typeof WebhooksRoute
  AdminGovernanceRoute: typeof AdminGovernanceRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRouteWithChildren
  DashboardPkiRoute: typeof DashboardPkiRoute
  DashboardS3Route: typeof DashboardS3Route
  DashboardWorkspacesRoute: typeof DashboardWorkspacesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRunsRunIdRoute: typeof DashboardRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workspaces': {
      id: '/dashboard/workspaces'
      path: '/dashboard/workspaces'
      fullPath: '/dashboard/workspaces'
      preLoaderRoute: typeof DashboardWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/s3': {
      id: '/dashboard/s3'
      path: '/dashboard/s3'
      fullPath: '/dashboard/s3'
      preLoaderRoute: typeof DashboardS3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pki': {
      id: '/dashboard/pki'
      path: '/dashboard/pki'
      fullPath: '/dashboard/pki'
      preLoaderRoute: typeof DashboardPkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/deployments': {
      id: '/dashboard/deployments'
      path: '/dashboard/deployments'
      fullPath: '/dashboard/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/governance': {
      id: '/admin/governance'
      path: '/admin/governance'
      fullPath: '/admin/governance'
      preLoaderRoute: typeof AdminGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/runs/$runId': {
      id: '/dashboard/runs/$runId'
      path: '/dashboard/runs/$runId'
      fullPath: '/dashboard/runs/$runId'
      preLoaderRoute: typeof DashboardRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/deployments/new': {
      id: '/dashboard/deployments/new'
      path: '/new'
      fullPath: '/dashboard/deployments/new'
      preLoaderRoute: typeof DashboardDeploymentsNewRouteImport
      parentRoute: typeof DashboardDeploymentsRoute
    }
  }
}

interface DashboardDeploymentsRouteChildren {
  DashboardDeploymentsNewRoute: typeof DashboardDeploymentsNewRoute
}

const DashboardDeploymentsRouteChildren: DashboardDeploymentsRouteChildren = {
  DashboardDeploymentsNewRoute: DashboardDeploymentsNewRoute,
}

const DashboardDeploymentsRouteWithChildren =
  DashboardDeploymentsRoute._addFileChildren(DashboardDeploymentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatusRoute: StatusRoute,
  WebhooksRoute: WebhooksRoute,
  AdminGovernanceRoute: AdminGovernanceRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  DashboardDeploymentsRoute: DashboardDeploymentsRouteWithChildren,
  DashboardPkiRoute: DashboardPkiRoute,
  DashboardS3Route: DashboardS3Route,
  DashboardWorkspacesRoute: DashboardWorkspacesRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRunsRunIdRoute: DashboardRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
